library(dplyr)

first_break <- function(df) {
  #overall data
  nba_df <- df
  #specific non overtime games
  non_over <- nba_df %>% 
    filter(first_break != 240) %>% 
    filter(mins == 240)
  
  ## first break shifted over one
  ## second break shifted over one
  shift_one_one <-  non_over %>% 
    filter(X.113 == 240) %>% 
    filter(X.227 == 240) %>% 
    mutate(h_drtg = h_ortg,
           h_ortg = h_usg,
           h_usg = h_tovp,
           h_tovp = h_blkp,
           h_blkp = h_stlp,
           h_stlp = h_astp,
           h_astp = h_trbp,
           h_trbp = h_drbp,
           h_drbp = h_orbp,
           h_orbp = h_ftr,
           h_ftr = h_3par,
           h_3par = h_efgp,
           h_efgp = h_tsp,
           h_tsp = second_break,
           second_break = X.227,
           h_points = h_pf,
           h_pf = h_tov,
           h_tov = h_blk,
           h_blk = h_stl,
           h_stl = h_ast, 
           h_ast = h_trb,
           h_trb = h_drb,
           h_drb = h_orb, 
           h_orb = h_ftp,
           h_ftp = h_fta, 
           h_fta = h_ft, 
           h_ft = h_3pp, 
           h_3pp = h_3pa,
           h_3pa = h_3p,
           h_3p = h_fgp, 
           h_fgp = h_fga,
           h_fga = h_fg,
           h_fg = mins.1,
           a_drtg = a_ortg,
           a_ortg = a_usg,
           a_tovp = a_usg,
           a_tovp = a_blkp,
           a_blkp = a_stlp,
           a_stlp = a_astp,
           a_astp = a_trbp,
           a_trbp = a_drbp,
           a_drbp = a_orbp,
           a_orbp = a_ftr,
           a_ftr = a_3par,
           a_3par = a_efgp,
           a_efgp = a_tsp,
           a_tsp = first_break,
           first_break = X.113)
  
  ## first break shifted over one
  ## second break shifted over two
  shift_one_two <-  non_over %>% 
    filter(X.113 == 240) %>% 
    filter(X.226 == 240) %>% 
    mutate(h_drtg = h_usg,
           h_ortg = h_tovp,
           h_usg = h_blkp,
           h_tovp = h_stlp,
           h_blkp = h_astp,
           h_stlp = h_trbp,
           h_astp = h_drbp,
           h_trbp = h_orbp,
           h_drbp = h_ftr,
           h_orbp = h_3par,
           h_ftr = h_efgp,
           h_3par = h_tsp,
           h_efgp = second_break,
           h_tsp = X.227,
           second_break = X.226,
           h_points = h_pf,
           h_pf = h_tov,
           h_tov = h_blk,
           h_blk = h_stl,
           h_stl = h_ast, 
           h_ast = h_trb,
           h_trb = h_drb,
           h_drb = h_orb, 
           h_orb = h_ftp,
           h_ftp = h_fta, 
           h_fta = h_ft, 
           h_ft = h_3pp, 
           h_3pp = h_3pa,
           h_3pa = h_3p,
           h_3p = h_fgp, 
           h_fgp = h_fga,
           h_fga = h_fg,
           h_fg = mins.1,
           a_drtg = a_ortg,
           a_ortg = a_usg,
           a_usg = a_tovp,
           a_tovp = a_blkp,
           a_blkp = a_stlp,
           a_stlp = a_astp,
           a_astp = a_trbp,
           a_trbp = a_drbp,
           a_drbp = a_orbp,
           a_orbp = a_ftr,
           a_ftr = a_3par,
           a_3par = a_efgp,
           a_efgp = a_tsp,
           a_tsp = first_break,
           first_break = X.113)
  
  ## first break shifted over one
  ## second break shifted over three
  shift_one_three <-  non_over %>% 
    filter(X.113 == 240) %>% 
    filter(X.225 == 240) %>% 
    mutate(h_drtg = h_tovp,
           h_ortg = h_blkp,
           h_usg = h_stlp,
           h_tovp = h_astp,
           h_blkp = h_trbp,
           h_stlp = h_drbp,
           h_astp = h_orbp,
           h_trbp = h_ftr,
           h_drbp = h_3par,
           h_orbp = h_efgp,
           h_ftr = h_tsp,
           h_3par = second_break,
           h_efgp = X.227,
           h_tsp = X.226,
           second_break = X.225,
           h_points = h_pf,
           h_pf = h_tov,
           h_tov = h_blk,
           h_blk = h_stl,
           h_stl = h_ast, 
           h_ast = h_trb,
           h_trb = h_drb,
           h_drb = h_orb, 
           h_orb = h_ftp,
           h_ftp = h_fta, 
           h_fta = h_ft, 
           h_ft = h_3pp, 
           h_3pp = h_3pa,
           h_3pa = h_3p,
           h_3p = h_fgp, 
           h_fgp = h_fga,
           h_fga = h_fg,
           h_fg = mins.1,
           a_drtg = a_ortg,
           a_ortg = a_usg,
           a_tovp = a_usg,
           a_tovp = a_blkp,
           a_blkp = a_stlp,
           a_stlp = a_astp,
           a_astp = a_trbp,
           a_trbp = a_drbp,
           a_drbp = a_orbp,
           a_orbp = a_ftr,
           a_ftr = a_3par,
           a_3par = a_efgp,
           a_efgp = a_tsp,
           a_tsp = first_break,
           first_break = X.113)
  
  ##first break shifted over two
  ## second break shifted over two
  shift_two_two <-  non_over %>% 
    filter(X.112 == 240) %>% 
    filter(X.226 == 240) %>% 
    mutate(h_drtg = h_usg,
           h_ortg = h_tovp,
           h_usg = h_blkp,
           h_tovp = h_stlp,
           h_blkp = h_astp,
           h_stlp = h_trbp,
           h_astp = h_drbp,
           h_trbp = h_orbp,
           h_drbp = h_ftr,
           h_orbp = h_3par,
           h_ftr = h_efgp,
           h_3par = h_tsp,
           h_efgp = second_break,
           h_tsp = X.227,
           second_break = X.226,
           h_points = h_tov,
           h_pf = h_blk,
           h_tov = h_stl,
           h_blk = h_ast,
           h_stl = h_trb, 
           h_ast = h_drb,
           h_trb = h_orb,
           h_drb = h_ftp, 
           h_orb = h_fta,
           h_ftp = h_ft, 
           h_fta = h_3pp, 
           h_ft = h_3pa, 
           h_3pp = h_3p,
           h_3pa = h_fgp,
           h_3p = h_fga, 
           h_fgp = h_fg,
           h_fga = mins.1,
           h_fg = a_drtg,
           a_drtg = a_usg,
           a_ortg = a_tovp,
           a_usg = a_blkp,
           a_tovp = a_stlp,
           a_blkp = a_astp,
           a_stlp = a_trbp,
           a_astp = a_drbp,
           a_trbp = a_orbp,
           a_drbp = a_ftr,
           a_orbp = a_3par,
           a_ftr = a_efgp,
           a_3par = a_tsp,
           a_efgp = first_break,
           a_tsp = X.113,
           first_break = X.112)
  
  ##first break shifted over two
  ## second break shifted over three
  shift_two_three <-  non_over %>% 
    filter(X.112 == 240) %>% 
    filter(X.225 == 240) %>% 
    mutate(h_drtg = h_tovp,
           h_ortg = h_blkp,
           h_tovp = h_stlp,
           h_tovp = h_astp,
           h_blkp = h_trbp,
           h_stlp = h_drbp,
           h_astp = h_orbp,
           h_trbp = h_ftr,
           h_drbp = h_3par,
           h_orbp = h_efgp,
           h_ftr = h_tsp,
           h_3par = second_break,
           h_efgp = X.227,
           h_tsp = X.226,
           second_break = X.225,
           h_points = h_tov,
           h_pf = h_blk,
           h_tov = h_stl,
           h_blk = h_ast,
           h_stl = h_trb, 
           h_ast = h_drb,
           h_trb = h_orb,
           h_drb = h_ftp, 
           h_orb = h_fta,
           h_ftp = h_ft, 
           h_fta = h_3pp, 
           h_ft = h_3pa, 
           h_3pp = h_3p,
           h_3pa = h_fgp,
           h_3p = h_fga, 
           h_fgp = h_fg,
           h_fga = mins.1,
           h_fg = a_drtg,
           a_drtg = a_usg,
           a_ortg = a_tovp,
           a_usg = a_blkp,
           a_tovp = a_stlp,
           a_blkp = a_astp,
           a_stlp = a_trbp,
           a_astp = a_drbp,
           a_trbp = a_orbp,
           a_drbp = a_ftr,
           a_orbp = a_3par,
           a_ftr = a_efgp,
           a_3par = a_tsp,
           a_efgp = first_break,
           a_tsp = X.113,
           first_break = X.112)
  
  ##first break shifted over two
  ## second break shifted over four
  shift_two_four <-  non_over %>% 
    filter(X.112 == 240) %>% 
    filter(X.224 == 240) %>% 
    mutate(h_drtg = h_blkp,
           h_ortg = h_stlp,
           h_tovp = h_astp,
           h_tovp = h_trbp,
           h_blkp = h_drbp,
           h_stlp = h_orbp,
           h_astp = h_ftr,
           h_trbp = h_3par,
           h_drbp = h_efgp,
           h_orbp = h_tsp,
           h_ftr = second_break,
           h_3par = X.227,
           h_efgp = X.226,
           h_tsp = X.225,
           second_break = X.224,
           h_points = h_tov,
           h_pf = h_blk,
           h_tov = h_stl,
           h_blk = h_ast,
           h_stl = h_trb, 
           h_ast = h_drb,
           h_trb = h_orb,
           h_drb = h_ftp, 
           h_orb = h_fta,
           h_ftp = h_ft, 
           h_fta = h_3pp, 
           h_ft = h_3pa, 
           h_3pp = h_3p,
           h_3pa = h_fgp,
           h_3p = h_fga, 
           h_fgp = h_fg,
           h_fga = mins.1,
           h_fg = a_drtg,
           a_drtg = a_usg,
           a_ortg = a_tovp,
           a_usg = a_blkp,
           a_tovp = a_stlp,
           a_blkp = a_astp,
           a_stlp = a_trbp,
           a_astp = a_drbp,
           a_trbp = a_orbp,
           a_drbp = a_ftr,
           a_orbp = a_3par,
           a_ftr = a_efgp,
           a_3par = a_tsp,
           a_efgp = first_break,
           a_tsp = X.113,
           first_break = X.112)
  
  
  ##first break shifted over two
  ## second break shifted over five
  shift_two_five <-  non_over %>% 
    filter(X.112 == 240) %>% 
    filter(X.223 == 240) %>% 
    mutate(h_drtg = h_stlp,
           h_ortg = h_astp,
           h_tovp = h_trbp,
           h_tovp = h_drbp,
           h_blkp = h_orbp,
           h_stlp = h_ftr,
           h_astp = h_3par,
           h_trbp = h_efgp,
           h_drbp = h_tsp,
           h_orbp = second_break,
           h_ftr = X.227,
           h_3par = X.226,
           h_efgp = X.225,
           h_tsp = X.224,
           second_break = X.223,
           h_points = h_tov,
           h_pf = h_blk,
           h_tov = h_stl,
           h_blk = h_ast,
           h_stl = h_trb, 
           h_ast = h_drb,
           h_trb = h_orb,
           h_drb = h_ftp, 
           h_orb = h_fta,
           h_ftp = h_ft, 
           h_fta = h_3pp, 
           h_ft = h_3pa, 
           h_3pp = h_3p,
           h_3pa = h_fgp,
           h_3p = h_fga, 
           h_fgp = h_fg,
           h_fga = mins.1,
           h_fg = a_drtg,
           a_drtg = a_usg,
           a_ortg = a_tovp,
           a_usg = a_blkp,
           a_tovp = a_stlp,
           a_blkp = a_astp,
           a_stlp = a_trbp,
           a_astp = a_drbp,
           a_trbp = a_orbp,
           a_drbp = a_ftr,
           a_orbp = a_3par,
           a_ftr = a_efgp,
           a_3par = a_tsp,
           a_efgp = first_break,
           a_tsp = X.113,
           first_break = X.112)
  
  ##first break shifted over three
  ## second break shifted over three
  shift_three_three <-  non_over %>% 
    filter(X.111 == 240) %>% 
    filter(X.225 == 240) %>% 
    mutate(h_drtg = h_tovp,
           h_ortg = h_blkp,
           h_tovp = h_stlp,
           h_tovp = h_astp,
           h_blkp = h_trbp,
           h_stlp = h_drbp,
           h_astp = h_orbp,
           h_trbp = h_ftr,
           h_drbp = h_3par,
           h_orbp = h_efgp,
           h_ftr = h_tsp,
           h_3par = second_break,
           h_efgp = X.227,
           h_tsp = X.226,
           second_break = X.225,
           h_points = h_blk,
           h_pf = h_stl,
           h_tov = h_ast,
           h_blk = h_trb,
           h_stl = h_drb, 
           h_ast = h_orb,
           h_trb = h_ftp,
           h_drb = h_fta, 
           h_orb = h_ft,
           h_ftp = h_3pp, 
           h_fta = h_3pa, 
           h_ft = h_3p, 
           h_3pp = h_fgp,
           h_3pa = h_fga,
           h_3p = h_fg, 
           h_fgp = mins.1,
           h_fga = a_drtg,
           h_fg = a_ortg,
           a_drtg = a_tovp,
           a_ortg = a_blkp,
           a_usg = a_stlp,
           a_tovp = a_astp,
           a_blkp = a_trbp,
           a_stlp = a_drbp,
           a_astp = a_orbp,
           a_trbp = a_ftr,
           a_drbp = a_3par,
           a_orbp = a_efgp,
           a_ftr = a_tsp,
           a_3par = first_break,
           a_efgp = X.113,
           a_tsp = X.112,
           first_break = X.111) 
  

  
  ##first break shifted over three
  ## second break shifted over four
  shift_three_four <-  non_over %>% 
    filter(X.111 == 240) %>% 
    filter(X.224 == 240) %>% 
    mutate(h_drtg = h_blkp,
           h_ortg = h_stlp,
           h_tovp = h_astp,
           h_tovp = h_trbp,
           h_blkp = h_drbp,
           h_stlp = h_orbp,
           h_astp = h_ftr,
           h_trbp = h_3par,
           h_drbp = h_efgp,
           h_orbp = h_tsp,
           h_ftr = second_break,
           h_3par = X.227,
           h_efgp = X.226,
           h_tsp = X.225,
           second_break = X.224,
           h_points = h_blk,
           h_pf = h_stl,
           h_tov = h_ast,
           h_blk = h_trb,
           h_stl = h_drb, 
           h_ast = h_orb,
           h_trb = h_ftp,
           h_drb = h_fta, 
           h_orb = h_ft,
           h_ftp = h_3pp, 
           h_fta = h_3pa, 
           h_ft = h_3p, 
           h_3pp = h_fgp,
           h_3pa = h_fga,
           h_3p = h_fg, 
           h_fgp = mins.1,
           h_fga = a_drtg,
           h_fg = a_ortg,
           a_drtg = a_tovp,
           a_ortg = a_blkp,
           a_usg = a_stlp,
           a_tovp = a_astp,
           a_blkp = a_trbp,
           a_stlp = a_drbp,
           a_astp = a_orbp,
           a_trbp = a_ftr,
           a_drbp = a_3par,
           a_orbp = a_efgp,
           a_ftr = a_tsp,
           a_3par = first_break,
           a_efgp = X.113,
           a_tsp = X.112,
           first_break = X.111)
  
  ##first break shifted over three
  ## second break shifted over five
  shift_three_five <-  non_over %>% 
    filter(X.111 == 240) %>% 
    filter(X.223 == 240) %>% 
    mutate(h_drtg = h_stlp,
           h_ortg = h_astp,
           h_tovp = h_trbp,
           h_tovp = h_drbp,
           h_blkp = h_orbp,
           h_stlp = h_ftr,
           h_astp = h_3par,
           h_trbp = h_efgp,
           h_drbp = h_tsp,
           h_orbp = second_break,
           h_ftr = X.227,
           h_3par = X.226,
           h_efgp = X.225,
           h_tsp = X.224,
           second_break = X.223,
           h_points = h_blk,
           h_pf = h_stl,
           h_tov = h_ast,
           h_blk = h_trb,
           h_stl = h_drb, 
           h_ast = h_orb,
           h_trb = h_ftp,
           h_drb = h_fta, 
           h_orb = h_ft,
           h_ftp = h_3pp, 
           h_fta = h_3pa, 
           h_ft = h_3p, 
           h_3pp = h_fgp,
           h_3pa = h_fga,
           h_3p = h_fg, 
           h_fgp = mins.1,
           h_fga = a_drtg,
           h_fg = a_ortg,
           a_drtg = a_tovp,
           a_ortg = a_blkp,
           a_usg = a_stlp,
           a_tovp = a_astp,
           a_blkp = a_trbp,
           a_stlp = a_drbp,
           a_astp = a_orbp,
           a_trbp = a_ftr,
           a_drbp = a_3par,
           a_orbp = a_efgp,
           a_ftr = a_tsp,
           a_3par = first_break,
           a_efgp = X.113,
           a_tsp = X.112,
           first_break = X.111)

  done_df <- rbind(shift_one_one, shift_one_two, shift_one_three,
                   shift_two_two, shift_two_three, shift_two_four,
                   shift_two_five, shift_three_three, shift_three_four,
                   shift_three_five) %>% 
    select(year,	month, date,	home,	away,	mins,	a_fg,	a_fga,
           a_fgp,	a_3p,	a_3pa,	a_3pp,	a_ft,	a_fta,	a_ftp,
           a_orb,	a_drb,	a_trb,	a_ast,	a_stl,	a_blk,	a_tov,
           a_pf,	a_points,	a_tsp,	a_efgp, a_ortg,	a_drtg,	h_fg,	h_fga,
           h_fgp,	h_3p,	h_3pa,	h_3pp,
           h_ft,	h_fta,	h_ftp,	h_orb,	h_drb,	h_trb,	h_ast,	h_stl,
           h_blk,	h_tov,	h_pf,	h_points,	h_tsp,	h_efgp,
           h_ortg,	h_drtg)
}
